version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    command: sleep infinity
    depends_on:
      - sqlserver
    volumes:
      - ..:/app
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
